services:
  - type: web
    name: oscar-shop
    env: python
    buildCommand: |
      poetry install --no-root
      poetry run python manage.py collectstatic --noinput
      poetry run python manage.py migrate --noinput
    startCommand: "poetry run gunicorn oscar_shop.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: SECRET_KEY
        value: "1234"
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "oscar-shop.onrender.com"
