services:
  - type: web
    name: oscar-shop
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn oscar_shop.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        value: "1234"
      - key: DEBUG
        value: "False"
      - key: DB_USER
        value: "oscarshoppost_user"
      - key: DB_PASSWORD
        value: "DBSxnQH6vucoWGE31KaECCIVgu8MKs1y"
      - key: DB_HOST
        value: "dpg-d1v7vak9c44c73dktk30-a.oregon-postgres.render.com"
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: "oscarshoppost"
      - key: ALLOWED_HOSTS
        value: "oscar-shop-3.onrender.com"
